version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd

  indexer:
    build: ../indexer
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGODB_URL: mongodb://root:passwd@mongo:27017/
    
  fastapi:
    build: ../api
    restart: always
    ports:
      - "80:8000"
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGODB_URL: mongodb://root:passwd@mongo:27017/

networks:
  default:
   external:
     name: intellisite
