version: "3.7"

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      MONGODB_DATABASE: intellisite

  indexer:
    build: ../indexer
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGODB_URL: mongodb://mongo:27017/intellisite
    
  fastapi:
    build: ../api
    restart: always
    ports:
      - "80:8000"
    environment:
      KAFKA_BROKER_URL: broker:9092
      DETECTIONS_TOPIC: intellisite.detections
      ALERTS_TOPIC: intellisite.alerts
      SUSPICIOUS_VEHICLE: SUV
      MONGODB_URL: mongodb://mongo:27017/intellisite
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: adminpasswd

networks:
  default:
   external:
     name: intellisite
